#-------------------------------------->>* txLcn-tm 分布式事务管理中心 *<<--------------------------------------#
server:
  port: 7970
spring:
  application:
    name: txlcn-tm
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql-server:3306/tx-manager?characterEncoding=UTF-8&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 数据库方言
    hibernate:
      ddl-auto: validate
  redis:
    host: redis-server
    port: 6379
    password:
tx-lcn:
  manager:
    admin-key: 123456                           # TM后台登录密码
    host: txlcn-tm                              # TM监听IP. 默认为 127.0.0.1
    port: 8070                                  # TxClient连接请求端口,TM监听Socket端口. 默认为 ${server.port} - 100
    heart-time: 30000                           # 心跳检测时间(ms). 默认为 300000
    dtx-time: 8000                              # 分布式事务执行总时间(ms). 默认为36000
    concurrent-level: 160                       # 事务处理并发等级. 默认为机器逻辑核心数5倍
    dtx-lock-time: ${tx-lcn.manager.dtx-time}   # 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
    seq-len: 12                                 # 雪花算法的sequence位长度，默认为12位.
    ex-url-enabled: false                       # 异常回调开关。开启时请制定ex-url
    # ex-url: /provider/email-to/949035443@qq.com # 事务异常通知（任何http协议地址。未指定协议时，为TM提供内置功能接口）。默认是邮件通知
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.hikari.driver-class-name}
    jdbc-url: ${spring.datasource.hikari.jdbc-url}
    username: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}
  message:
    netty:
      attr-delay-time: ${tx-lcn.manager.dtx-time}   # 参数延迟删除时间单位ms  默认为dtx-time值
