server:
  port: 8010

spring:
  application:
    name: elasticsearch-api
  http:
    encoding:                                     # 编码配置
      force: true
      charset: UTF-8
      enabled: true

elasticsearch-configuration:
  connect-timeout: -1
  socket-timeout: -1
  connection-request-timeout: -1
  hosts:
    - port: 9200
      schema: http
      hostname: 127.0.0.1


