server:
  port: 8010

spring:
  application:
    name: elasticsearch-api
  http:
    encoding:                                     # 编码配置
      force: true
      charset: UTF-8
      enabled: true

elasticsearch-configuration:
  hosts:
    - host: 192.168.232.110
      port: 9200
      schema: http


