# 中间件服务器设置
server:
  port: 8080
  servlet:
    context-path: /xxl-job-admin

# spring配置
spring:
  application:
    name: xxl-job-admin
  http:
    encoding:                                     # 编码配置
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/xxl_job?characterEncoding=UTF-8&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      connection-test-query: select 1
  mail:
    host: xxx
    port: 25
    username: xxx
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

# actuator配置
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

# mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
  type-aliases-package: com.xxl.job.admin.core.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # mybatis sql日志打印
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
