#-------------------------------------->>* Eureka-Server 注册中心 节点2 *<<--------------------------------------#
server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  server:
    peer-node-read-timeout-ms: 3000   # 设置超时响应时间
  client:
    register-with-eureka: false # false是不向注册中心注册自己
    fetch-registry: false       # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/  # 集群配置

