#-------------------------------------->>* Eureka-Server 注册中心 *<<--------------------------------------#
spring:
  application:
    name: eureka-server     # 微服务名称
  profiles:
    active: eureka          # 环境配置文件


