version: '2'
services:

  eureka:
    image: eureka-server:2.0.0
    container_name: eureka
    restart: always
    hostname: eureka
    networks:
      - base_net
    ports:
      - 8761:8761
    environment:
      - spring.profiles.active=eureka

networks:
  base_net:
    external: true
