version: '2'
services:

  gitlab:
    image: twang2218/gitlab-ce-zh:latest
    container_name: gitlab
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /docker/volume/gitlab/config:/etc/gitlab
      - /docker/volume/gitlab/logs:/var/log/gitlab
      - /docker/volume/gitlab/data:/var/opt/gitlab
    privileged: true
    hostname: gitlab
    networks:
      - base_net

networks:
  base_net:
    external: true
