version: '2'
services:

  config-server:
    image: config-server:2.0.0
    container_name: config-server
    hostname: config-server
    networks:
      - base_net
    ports:
      - 3344:3344

networks:
  base_net:
    external: true
