version: '2'
services:
  es:
    image: elasticsearch:7.6.0
    container_name: es
    hostname: es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/docker/container/es/single/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/esdata/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

networks:
  elastic:
    driver: bridge